name:                lorentz-example
version:             0.1.0.0
github:              "githubuser/lorentz-example"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base-noprelude >= 4.7 && < 5
- containers
- morley
- morley-prelude

library:
  source-dirs: src

executables:
  lorentz-example-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lorentz-example

