resolver: lts-13.22

packages:
- .
- location:
    git: https://gitlab.com/morley-framework/morley.git
    commit: f448cefc4815bbcbd8f258ac84097a1837da7767
  subdirs:
  - ./
  - prelude
  extra-dep: true

extra-deps:
- aeson-options-0.1.0
- base58-bytestring-0.1.0
- hex-text-0.1.0.0
